setup C++ and release CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,11 +1,12 @@
-name: lint
-
+name: CI
 
 permissions:
   contents: read
 
 env:
   CARGO_TERM_COLOR: always
+  RUST_BACKTRACE: 1
+  VCPKG_BINARY_SOURCES: clear
 
 on:
   push:
@@ -48,11 +49,16 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        os:
-          - ubuntu-latest
-          # macos-14 for M1 runners
-          - macos-14
-          - ubuntu-24.04-arm
+        include:
+          - os: ubuntu-latest
+            vcpkg_triplet: x64-linux
+            cmake_preset: debug-linux
+          - os: macos-14 # macos-14 for M1 runners
+            vcpkg_triplet: arm64-osx
+            cmake_preset: debug-osx-arm64
+          - os: ubuntu-24.04-arm
+            vcpkg_triplet: arm64-linux
+            cmake_preset: debug-linux
     steps:
       - uses: actions/checkout@v4
 
@@ -64,17 +70,15 @@ jobs:
       - uses: Swatinem/rust-cache@v2
 
       - uses: taiki-e/install-action@nextest
+      - uses: extractions/setup-just@v3
 
       - name: Build
-        run: cargo build
+        run: just build
 
       - name: nextest
         run: cargo nextest run --profile ci
 
       - name: Upload JUnit report
-        # Run this step even if the test step fails. Upload it right now because
-        # we're most interested in the JUnit report generated by the local
-        # version of nextest, not the latest release.
         if: '!cancelled()'
         uses: actions/upload-artifact@v4.6.2
         with:
@@ -84,12 +88,59 @@ jobs:
             target/nextest/ci/junit.xml
           if-no-files-found: error
 
-      - name: Upload nextest binary
+      - uses: lukka/get-cmake@latest
+        with:
+          cmakeVersion: '3.31'
+      - name: setup ccache
+        uses: hendrikmuhs/ccache-action@v1.2
+        with:
+          create-symlink: true
+
+      - name: Setup vcpkg
+        uses: lukka/run-vcpkg@v11
+
+      - name: Setup C++ environment
+        run: |
+          echo "VCPKG_TARGET_TRIPLET=${{ matrix.vcpkg_triplet }}" >> $GITHUB_ENV
+          echo "VCPKG_TOOLCHAIN_PATH=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" >> $GITHUB_ENV
+
+          TRIPLET_FILE="$VCPKG_ROOT/triplets/${{ matrix.vcpkg_triplet }}.cmake"
+
+          if [ ! -f "$TRIPLET_FILE" ]; then
+              echo "Triplet file not found. Attempting to download..."
+              mkdir -p "$(dirname "$TRIPLET_FILE")"
+
+              BASE_URL="https://raw.githubusercontent.com/microsoft/vcpkg/refs/heads/master/triplets"
+              URLS=("$BASE_URL/${{ matrix.vcpkg_triplet }}.cmake" "$BASE_URL/community/${{ matrix.vcpkg_triplet }}.cmake")
+
+              for url in "${URLS[@]}"; do
+                  echo "Trying to download from: $url"
+                  if wget --spider "$url" 2>/dev/null && wget -O "$TRIPLET_FILE" "$url"; then
+                      echo "Downloaded from: $url"
+                      break
+                  fi
+              done
+
+              [ ! -f "$TRIPLET_FILE" ] && { echo "Error: Could not download triplet file"; exit 1; }
+          fi
+
+          exit 0
+
+      - name: Setup Cmake
+        run: just cmake
+        working-directory: cpp
+      - name: Build C++
+        run: just build
+        working-directory: cpp
+      - name: Run C++ tests
+        run: just test
+        working-directory: cpp
+      - name: Upload binary
         uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
         with:
           retention-days: 7
           compression-level: 9
-          name: cargo-nextest-${{ matrix.os }}
+          name: rust-tvtf-${{ matrix.os }}
           path: |
             target/debug/librust_tvtf.dylib
             target/debug/librust_tvtf.so
